[package]
name = "write-fonts"
version = "0.1.11"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Writing font files."
repository = "https://github.com/googlefonts/fontations"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
font-types = { version = "0.1.4", path = "../font-types" }
read-fonts = { version = "0.1.4", path = "../read-fonts" }
bitflags = "1.3"
kurbo = "0.9.1"

[dev-dependencies]
diff = "0.1.12"
ansi_term = "0.12.1"
font-test-data = { path = "../font-test-data" }
read-fonts = { version = "0.1.4", path = "../read-fonts", features = [ "codegen_test"] }
log = "0.4"
env_logger = "0.10.0"
yare = "1.0.2"
